---
#Use Ansible to configure your 'primary Ethernet interface' as follows:

#interface description:     *** IN USE ***
#switchport mode:          access
#VLAN:                           <one of the VLANs created in exercise1>

#Your 'primary Ethernet interface' is specified in your ~/ansible-hosts file.

- name: Create Arista VLANs
  hosts: arista

  tasks:
    - name: configure primary interface
      eos_switchport: name=Ethernet3 mode=access access_vlan:501
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{ eapi_port }}
           transport=https

      eos_ethernet: name=Ethenet3 description="*** IN USE ***"
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{ eapi_port }}
           transport=https
