---

#Use the cisco_file_transfer.py module to transfer a small file to the Cisco pynet-rtr1 router.

- name: Copy file to Cisco router
  hosts: pynet-rtr1
  gather_facts: False

  tasks:
  - name: File Transfer
    cisco_file_transfer:
        source_file="/home/eaboytes/ANSIBLE/cisco_file.txt"
        dest_file=eaboytes1.txt
        overwrite=true
        enable_scp=true
        host={{ host }}
        port={{ port }}
        username={{ username }}
        password={{ password }}