---
#
# Create an Ansible playbook that generates five switch configurations based upon the below partial
# switch configuration. The hostname, ip_addr, and default_gateway should be unique for each switch.
#
# $ ansible-playbook site.yml
# 
- name: Generate configuration file
  hosts : local
  roles:
    - access_switch
